name: desktop-capture-preview
version: '0.1'
summary: Desktop Capture Electron app
description: |
  Desktop Capture Electron app as an example
base: core22
confinement: strict
grade: stable

apps:
  desktop-capture-preview:
    command: desktop-capture-preview/desktop-capture-preview --no-sandbox
    extensions: [gnome]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
      # PipeWire requirements
      SPA_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/spa-0.2
      PIPEWIRE_CONFIG_NAME: $SNAP/usr/share/pipewire/pipewire.conf
      PIPEWIRE_MODULE_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3

layout:
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

parts:
  desktop-capture-preview:
    plugin: nil
    source: https://github.com/aiddya/desktop-capture-preview.git
    after:
    - pipewire
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        chmod -R og+rwX ./desktop-capture-preview-linux-*
        cp -rv ./desktop-capture-preview-linux-* $SNAPCRAFT_PART_INSTALL/desktop-capture-preview
        chmod og+x $SNAPCRAFT_PART_INSTALL/desktop-capture-preview/desktop-capture-preview
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4

  pipewire:
    plugin: nil
    build-packages: [libpipewire-0.3-dev]
    stage-packages: [pipewire]
    prime:
      - usr/lib/*/pipewire-*
      - usr/lib/*/spa-*
      - usr/lib/*/libpipewire*.so*
      - usr/share/pipewire
